### ISSUE TITLE
This is great, but I have one small issue i hope you can help with

### ISSUE THREAD

**Issue by KerryRK** [cgsmith/zf1-recaptcha-2#21]
Hi thanks for this, work a treat. However, I am having an issue in that the captcha is at the top of the form not at the bottom besides the submit button. Maybe I have been looking at this for far too long but I cannot see what the issue is. Any thoughts?
![image](https://user-images.githubusercontent.com/40751163/42146054-92b19aec-7e08-11e8-93d6-443b709957a6.png)

**Comment by cgsmith** [comment]
This should be fixable with css or adjusting your view.
