### ISSUE TITLE
Naming problems

### ISSUE THREAD

**Issue by xorock** [cgsmith/zf1-recaptcha-2#3]
Thank You for Your work.

I found some errors inside code.
Class Cgsmith\Validate\ValidateRecaptcha should be named 'Recaptcha' or Zend will not load it.
Because You are using namespaces every Zend_Exception should be executed as \Zend_Exception.

That's alle I think.

**Comment by cgsmith** [comment]
Thanks @xorock 

I updated the code and pushed it to 1.0.1
